### ISSUE TITLE
Private block chain error: --datadir: command not found error

### ISSUE THREAD

**Issue by warren8r** [Shivamnema/Supply-Chain-Management-BlockChain-UseCase#1]
Hello,
I am trying/testing your app, but I am running into the following error when creating the private block chain: "--datadir: command not found"
I am new to this, but the syntax seems ok. Not sure what the problems?
Any help would be greatly appreciated.
Thanks

**Comment by Shivamnema** [comment]
Could you please refer to my medium article for setting up private
blockchain. If you still get some errors please get back to me with
screenshots.

https://medium.com/@thenanobyte/how-to-deploy-the-smart-contract-on-private-ethereum-network-using-geth-66586b53b06e

**Comment by warren8r** [comment]
I will do this. Thank you so much!

**Comment by warren8r** [comment]
Hello,
Step 6 is causing Geth to continually run, which means I cannot run step 7. Shall I interrupt step 6 to run step 7?
![image](https://user-images.githubusercontent.com/15840417/37937544-00989084-310f-11e8-9832-6ff1eb7de114.png)

**Comment by Shivamnema** [comment]
Actually, you can. Though that is downloading the ethereum blockchain data
on your system. You should avoid that. Please put the commands carefully it
will open up JavaScript console.

**Comment by warren8r** [comment]
Hello,
I am just copy and pasting your command and getting an endless stream of etherium status. I notice in your screenshot that you are only getting a few lines before the console opens. Mine has not stopped. I am also seeing a synchronization error at the end. Here is a screenshot:
![screenshot from 2018-03-27 11-50-24](https://user-images.githubusercontent.com/15840417/37988255-4b15a07e-31b5-11e8-8a08-cf771a71057e.png)

**Comment by Shivamnema** [comment]
Indeed. As I mentioned it ia downloading the ethereum blockchain on your
system. Please check genesis.json file and all the config files it should
work that way as for me.

**Comment by warren8r** [comment]
Thank you for your help. I will re-try your suggestions and keep you posted.
Just curious, are you in the US? Are you reachable by WhatsAPP?
Thank you!
Matt

**Comment by warren8r** [comment]
Hello,
Just wanted to give my progress: I have finished all steps up to and including 8C. Now getting the following error running 8D (see last few lines). Can you guide me on what I need to do? Not sure how to unlock: 
![screenshot from 2018-03-27 15-40-15](https://user-images.githubusercontent.com/15840417/37998998-cf48ea34-31d5-11e8-8782-92a6c556a77f.png)

Are you available on WhatsApp or TeamViewer?
Thanks for all of your help - your assistance is GREATLY appreciated.
Thanks! -Matt

**Comment by Shivamnema** [comment]
Hey, Great Work.
