### ISSUE TITLE
Running out of gas

### ISSUE THREAD

**Issue by warren8r** [Shivamnema/Supply-Chain-Management-BlockChain-UseCase#2]
Hello,
I have been trying to deploy this smart contract for almost a week now and I keep running into some trouble. I have a question:
1. Is there a way to have an infinite amount of gas so I don't run out? Or is there a way to change the cost of transactions to 0? Remix IDE keeps saying I have run out of gas.
    Thank you for your help!

**Comment by Shivamnema** [comment]
Hey,
Firstly, You can earn the sufficient amount of gas by executing `miner.start()` for a while and then stop using `miner.stop()`. 
Secondly, No you cannot change the cost of a transaction to 0.
