### ISSUE TITLE
Create Chain didnt stop and console not working.

### ISSUE THREAD

**Issue by bensonkb** [Shivamnema/Supply-Chain-Management-BlockChain-UseCase#3]
Create Chain Didnt work.
Create local chain:
[Link](https://github.com/Shivamnema/Supply-Chain-Management-BlockChain-UseCase#create-local-chain)
Type error in –nodeiscover.
Local Chain keeps on creating.
[Link](https://github.com/Shivamnema/Supply-Chain-Management-BlockChain-UseCase#create-new-account-in-geth-console)
Console is not created.

**Comment by Shivamnema** [comment]
Could you please explain the problem thoroughly. Also, Please attach the screenshots as well.

**Comment by bensonkb** [comment]
There are Spelling mistake in the Create local chain: Command:
Need to change –nodeiscover to --nodiscover and - as --

**Comment by saiffya** [comment]
Yes you are right @bensonkb

**Comment by Shivamnema** [comment]
@bensonkb Thanks for improvement.

**Comment by Shivamnema** [comment]
Closing the Issue.
