### ISSUE TITLE
Test Casse Login Not working

### ISSUE THREAD

**Issue by bensonkb** [Shivamnema/Supply-Chain-Management-BlockChain-UseCase#4]
Not Able to Login with the Test case Login Provided.
`node server.js

Example app listening at http://:::5000

T: Manufacturer  : 100   qwerty P:  false

T: Manufacturer  : 100   qwerty P:  false

T: Manufacturer  : 100   qwerty P:  false
`
![screenshot from 2018-05-29 16-54-06](https://user-images.githubusercontent.com/4044180/40657777-bb6add84-6366-11e8-9f37-b48a6a18389d.png)
After login Failed url redirect to
![screenshot from 2018-05-29 16-54-23](https://user-images.githubusercontent.com/4044180/40657808-d2c69c66-6366-11e8-9ad3-a0571c1edf2f.png)

**Comment by Shivamnema** [comment]
Apologies for the late response. If your problem is not solved yet please re-open the issue again. As of now, As I didn't faced anything like this. Thus I'm closing this issue. Feel free to reach out.

**Comment by s-a-c-h-i-n** [comment]
How did you resolve this issue?

**Comment by bensonkb** [comment]
@s-a-c-h-i-n : Issue is not resolved. he just closed the issue.

**Comment by Shivamnema** [comment]
@bensonkb Did you tried registering it first?
