### ISSUE TITLE
invalid command: "–rpc"

### ISSUE THREAD

**Issue by shalikpatel** [Shivamnema/Supply-Chain-Management-BlockChain-UseCase#6]
After installing all package I am getting invalid command: "-rpc" 

shalikram@shalikram-HP-Pavilion-g4-Notebook-PC:~$ geth –rpc –rpcport “8085” --rpcapi=”db,eth,net,web3,personal,web3” --datadir data –networkid 123 –nodeiscover –maxpeers 0 init genesis.json
invalid command: "–rpc"

**Comment by Ashok-Sandhyala** [comment]
I am also facing same problem

**Comment by Shivamnema** [comment]
I've not tested this application in a long time. --rpc might've been removed. Please create a PR for the solution.

**Comment by Shivamnema** [comment]
@Ashok-Sandhyala Please check the geth documentation for --rpc.

**Comment by Shivamnema** [comment]
@Ashok-Sandhyala Please use _nodiscover_  instead of nodeiscover. Also use `--` if it seems like a long hypen.

**Comment by Shivamnema** [comment]
Closing this issue.
